training_data = [
    ("Hola", "¡Hola! ¿En qué puedo ayudarte hoy?"),
    ("Buenos días", "¡Buenos días! Espero que tengas una excelente jornada."),
    ("Buenas tardes", "¡Buenas tardes! ¿Cómo va todo por aquí?"),
    ("Buenas noches", "¡Buenas noches! ¿En qué puedo asistirte antes de terminar el día?"),
    ("¿Cómo estás?", "¡Muy bien, gracias por preguntar! ¿Y tú?"),
    ("¿Qué tal?", "¡Todo bien! ¿Y por tu lado?"),
    ("Hola, ¿hay alguien?", "¡Hola! Sí, aquí estoy para lo que necesites."),
    ("Buen día", "¡Buen día! ¿Qué tenemos para hoy?"),
    ("Hey", "¡Hola! ¿Cómo te va?"),
    ("Buenas", "¡Buenas! ¿En qué te puedo colaborar?"),
    ("¡Hola, bot!", "¡Hola! Siempre listo para ayudar. Cuéntame."),
    ("¿Cómo va la cosa?", "Todo marchando bien, ¿en qué te puedo apoyar?"),
    ("¿Qué cuentas?", "Aquí listo para trabajar contigo. ¿Tú qué tal?"),
    ("Hola, ¿me escuchas?", "¡Fuerte y claro! ¿En qué puedo servirte?"),
    ("Saludos", "¡Saludos! Qué gusto saludarte."),
    ("¡Qué más!", "¡Todo excelente! ¿Cómo va tu día?"),
    ("Buenísimos días", "¡Muy buenos días! Que sea un día muy productivo."),
    ("Hola, mucho gusto", "¡El gusto es mío! ¿En qué te puedo ayudar?"),
    ("Hola, buen día", "¡Hola! Muy buen día para ti también."),
    ("¿Qué hubo?", "¡Hola! ¿Todo bien por allá?"),
    ("Hola, ¿cómo va todo?", "¡Hola! Todo marcha muy bien, gracias. ¿Y tú cómo vas?"),
    ("Buenas, ¿cómo le va?", "¡Muy bien! Gracias por el saludo. ¿En qué le puedo servir?"),
    ("Hola, ¿estás disponible?", "¡Claro que sí! Estoy a tu disposición."),
    ("Cordial saludo", "Recibe también un cordial saludo. ¿En qué puedo colaborar hoy?"),
    ("Hola, amigo", "¡Hola! Aquí estoy para darte una mano."),
    ("¿Qué tal tu día?", "Va muy bien, ¡gracias! Espero que el tuyo también."),
    ("Hola, ¿qué haces?", "Aquí atento a tus preguntas. ¿En qué te ayudo?"),
    ("Buenas tardes, ¿cómo está?", "Muy bien, muchas gracias. ¿Cómo puedo asistirte hoy?"),
    ("¡Hola, hola!", "¡Hola! Qué buena energía. ¿En qué te colaboro?"),
    ("Hola, ¿qué hay de nuevo?", "¡Hola! Todo listo por aquí para empezar. ¿Tú dirás?"),
    ("Buenos días, ¿qué tal?", "¡Buenos días! Todo excelente, gracias por preguntar."),
    ("Buenas, ¿me ayudas?", "¡Por supuesto! Cuéntame qué necesitas."),
    ("Hola, espero que estés bien", "¡Muchas gracias! Igualmente para ti. ¿En qué puedo ayudarte?"),
    ("¿Se puede?", "¡Claro que sí! Adelante, ¿en qué te ayudo?"),
    ("Hola, compañero", "¡Hola! Aquí firme para apoyarte en lo que necesites."),
    ("¡Buenas, buenas!", "¡Hola! Qué gusto saludarte de nuevo."),
    ("Hola, ¿cómo amaneciste?", "¡Muy bien! Con toda la energía para hoy. ¿Y tú?"),
    ("¿Qué onda?", "¡Hola! ¿Cómo va todo?"),
    ("Buen día, ¿cómo va el trabajo?", "¡Hola! Por aquí todo rindiendo mucho. ¿En qué te apoyo?"),
    ("Hola, quisiera hacer una consulta", "¡Hola! Con gusto, dime qué duda tienes."),
    ("Buenas, ¿estás ahí?", "¡Aquí estoy! Listo para lo que necesites."),
    ("Hola, un saludo", "¡Hola! Muchas gracias por el saludo."),
    ("¿Cómo te trata la vida?", "¡Muy bien! Con ganas de ayudar. ¿Y a ti?"),
    ("Hola, ¿cómo se encuentra?", "¡Muy bien, gracias! ¿En qué puedo serle útil hoy?"),
    ("¡Hola, qué tal todo!", "¡Hola! Todo de maravilla por aquí."),
    ("Buenas, gusto en saludarte", "¡Igualmente! Es un placer saludarte hoy."),
    ("Hola, ¿cómo va la jornada?", "¡Va muy bien! ¿En qué puedo colaborar en tu jornada?"),
    ("Buenos días, ¿me regalas un momento?", "¡Claro! Todo el tiempo que necesites."),
    ("Hola, ¿cómo va la mañana?", "¡Excelente! Muy productiva. ¿Y la tuya?"),
    ("Buenas tardes, ¿me podrías ayudar?", "¡Claro que sí! Dime en qué puedo apoyarte."),
    ("Hola, ¿qué tal amaneció?", "¡Muy bien! Con mucho ánimo. ¿Cómo amaneciste tú?"),
    ("Buenas, ¿qué tal el clima por allá?", "¡Por aquí todo bien! ¿En qué te puedo asistir?"),
    ("Hola, ¿cómo te ha ido?", "¡Muy bien! Gracias por saludar. ¿A ti cómo te va?"),
    ("Buenos días, ¿en qué andas?", "Aquí atento a tus solicitudes. ¿Qué necesitas?"),
    ("Hola, ¿estás libre?", "¡Totalmente! Soy todo oídos."),
    ("¡Saludos desde el campo!", "¡Qué bueno! Un gran saludo de vuelta para allá."),
    ("Hola, ¿cómo marchan las cosas?", "¡Todo marchando sobre ruedas! ¿Y las tuyas?"),
    ("Buenas, ¿podemos hablar?", "¡Por supuesto! Cuéntame qué tienes en mente."),
    ("Hola, ¿cómo va la tarde?", "¡Muy tranquila y productiva! ¿Y la tuya?"),
    ("¿Cómo va ese ánimo?", "¡Al cien por ciento! ¿Y el tuyo?"),
    ("Hola, ¿qué tal la semana?", "¡Va excelente! ¿Cómo va la tuya?"),
    ("Buenas, ¿un momento por favor?", "¡Claro! Dime en qué te puedo ayudar."),
    ("Hola, ¿qué cuentas de nuevo?", "¡Nada por ahora, listo para servirte!"),
    ("Buenos días, ¿cómo va el café?", "¡Saliendo apenas! ¿En qué te puedo ayudar hoy?"),
    ("Hola, bendiciones", "¡Muchas gracias! Igualmente para ti. ¿En qué te apoyo?"),
    ("Buenas, ¿me escuchas bien?", "¡Sí, te escucho perfecto! ¿Qué necesitas?"),
    ("Hola, ¿cómo va el equipo?", "¡Todos listos para trabajar! ¿En qué te ayudamos?"),
    ("Hola, un placer saludarte", "¡El placer es mío! ¿Qué puedo hacer por ti?"),
    ("Buenas, ¿cómo va la vida?", "¡Todo muy bien! Disfrutando el día. ¿Y tú?"),
    ("Hola, ¿qué tal todo por allá?", "¡Todo bajo control! ¿En qué te colaboro?"),
    ("Buenos días, ¿cómo vas hoy?", "¡Con mucha energía! ¿Cómo vas tú?"),
    ("Hola, ¿estás activo?", "¡Claro que sí! Siempre disponible."),
    ("Buenas, ¿qué me cuentas?", "Aquí esperando tus instrucciones. ¿Qué hay para hoy?"),
    ("Hola, ¿cómo va la labor?", "¡Rindiendo bastante! ¿En qué te puedo asistir?"),
    ("Buenos días, ¿qué hay de bueno?", "¡Muchas cosas! ¿En qué empezamos hoy?"),
    ("Hola, un gusto verte", "¡Igualmente! Aunque sea de forma digital. ¿Qué necesitas?"),
    ("Buenas, ¿me das una mano?", "¡Claro que sí! Para eso estoy."),
    ("Hola, ¿cómo va el ambiente?", "¡Muy positivo por aquí! ¿Y por allá?"),
    ("Hola, ¿cómo estás tú hoy?", "¡Excelente y listo para ayudar! ¿Y tú?"),
    ("Buenas, ¿me prestas atención?", "¡Toda mi atención es tuya! Cuéntame."),
    ("Hola, ¿cómo va la cosecha?", "¡Espero que excelente! ¿En qué te puedo colaborar?"),
    ("Buenos días, ¿qué tal el día?", "¡Pinta muy bien! ¿En qué te ayudo?"),
    ("Hola, ¿qué tal la energía?", "¡Muy alta! ¿En qué la enfocamos hoy?"),
    ("Buenas, ¿me regalas un minuto?", "¡El tiempo que necesites! Dime."),
    ("Hola, ¿qué tal la vuelta?", "¡Todo bien! ¿En qué te puedo servir?"),
    ("Hola, ¿cómo va el proceso?", "¡Avanzando! ¿En qué puedo apoyarte hoy?"),
    ("Buenas, ¿cómo va el lunes?", "¡Con toda la actitud de inicio de semana!"),
    ("Hola, ¿cómo va el viernes?", "¡Con la alegría de cerrar bien la semana!"),
    ("Hola, ¿cómo te trata el jueves?", "¡Muy bien! Ya casi terminando la semana laboral."),
    ("Buenas, ¿me ayudas con algo?", "¡Por supuesto! Cuéntame de qué se trata."),
    ("Hola, ¿qué tal el descanso?", "¡Espero que haya sido reparador! ¿En qué te ayudo?"),
    ("Buenos días, ¿listo para trabajar?", "¡Más que listo! ¿Por dónde empezamos?"),
    ("Hola, ¿cómo va el avance?", "¡Muy bien! ¿En qué te puedo asistir ahora?"),
    ("Buenas, ¿qué tal la charla?", "¡Siempre listo para conversar! Dime."),
    ("Hola, ¿cómo va el proyecto?", "¡Avanzando firme! ¿En qué te apoyo?"),
    ("Hola, ¿qué tal el grupo?", "¡Todos muy motivados! ¿En qué te colaboro?"),
    ("Buenas, ¿cómo va la capacitación?", "¡Espero que sea de gran provecho! ¿En qué te ayudo?"),
    ("Hola, ¿estás pendiente?", "¡Siempre atento! ¿Qué necesitas?"),
    ("Buenos días, ¿cómo va la planeación?", "¡Marchando bien! ¿En qué te puedo dar una mano?"),
    ("Hola, ¿en qué andamos?", "¡Aquí listo para cualquier tarea! ¿Tú dirás?")
  ]